### ISSUE TITLE
Move the SRC folder to a new file named portfolio or <ProjectName> something

### ISSUE THREAD

**Issue by Rohithv07** [Rohithv07/ShowUp#3]
Currently the src folder will be belonged to a new project, move the entire folder to a new project to indicate it is a separate individual project and submit a MR.

**Comment by Sanjayshreeram** [comment]
can u assign it to me ?

**Comment by Rohithv07** [comment]
@Sanjayshreeram thanks, you can create a new issue and raise a MR.

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can u assign me.

**Comment by Rohithv07** [comment]
Please, create MR's. Thanks everyone
